# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('href', models.URLField(verbose_name='link')),
                ('status', models.PositiveIntegerField(choices=[(1, 'normal'), (0, 'delete')], default=1, verbose_name='status')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='weight is bigger, order forward', verbose_name='weight')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'link',
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, 'latest articles'), (3, 'hot articles'), (4, 'recent articles')], default=1, verbose_name='show type')),
                ('content', models.CharField(blank=True, help_text='if setting is not HTML, it can be NULL', max_length=500, verbose_name='content')),
                ('status', models.PositiveIntegerField(choices=[(1, 'show'), (0, 'hide')], default=1, verbose_name='status')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='weight is bigger, order forward', verbose_name='weight')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'sidebar',
                'verbose_name_plural': 'sidebar',
            },
        ),
    ]
