# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-29 04:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='if setting is not HTML type, it can be NULL', max_length=500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
